// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcQrfDIRakNR02oBrIUApEK2DNLQZxCyM',
    appId: '1:18369224300:web:a050f85e47e09b33db0249',
    messagingSenderId: '18369224300',
    projectId: 'srilankaapp-4abc5',
    authDomain: 'srilankaapp-4abc5.firebaseapp.com',
    storageBucket: 'srilankaapp-4abc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARUm2enn9NeALrd5Eac70NoSForeTJrJY',
    appId: '1:18369224300:android:3d6c5acb85258452db0249',
    messagingSenderId: '18369224300',
    projectId: 'srilankaapp-4abc5',
    storageBucket: 'srilankaapp-4abc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4qZ12xVhi9Gicwd5xhgW--iS9yxnqHo',
    appId: '1:18369224300:ios:536deab2adf09a89db0249',
    messagingSenderId: '18369224300',
    projectId: 'srilankaapp-4abc5',
    storageBucket: 'srilankaapp-4abc5.firebasestorage.app',
    iosBundleId: 'com.srilanka.sriLankaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4qZ12xVhi9Gicwd5xhgW--iS9yxnqHo',
    appId: '1:18369224300:ios:536deab2adf09a89db0249',
    messagingSenderId: '18369224300',
    projectId: 'srilankaapp-4abc5',
    storageBucket: 'srilankaapp-4abc5.firebasestorage.app',
    iosBundleId: 'com.srilanka.sriLankaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcQrfDIRakNR02oBrIUApEK2DNLQZxCyM',
    appId: '1:18369224300:web:8a9e86c2fa0477b4db0249',
    messagingSenderId: '18369224300',
    projectId: 'srilankaapp-4abc5',
    authDomain: 'srilankaapp-4abc5.firebaseapp.com',
    storageBucket: 'srilankaapp-4abc5.firebasestorage.app',
  );
}
